### ISSUE TITLE
github page

### ISSUE THREAD

**Issue by zeffii** [zeffii/mesh_tiny_cad#40]
http://zeffii.github.io/mesh_tinyCAD

**Comment by Spirou4D** [comment]
Hi  Zefii,

About your icons version fo TinyCAD, I have installed in my Blender 2.77 last release and I have this traceback:
`Traceback (most recent call last):
  File "/usr/share/blender/2.77/scripts/modules/addon_utils.py", line 331, in enable
    mod.__time__ = os.path.getmtime(mod.__file__)
AttributeError: module 'mesh_tinyCAD' has no attribute '__file__'`

I think it's about the global variable '__file__' that don't know Blender!!! Weird, not? In your __init__ file you use this variable but normally Blender must know this, not?

**Comment by zeffii** [comment]
Hi @Spirou4D 

I should probably delete the icon branch version - it is highly unstable. (Even If you installed it correctly, it requires a different install process compared to the master branch) .

Please consider the icons version unsupported. It is broken in a way that I can not fix.

**Comment by Spirou4D** [comment]
No no it's me, I have installed in my Linux and havn't changed the right on the files.
I love your icons, better to use TinyCAD!

**Comment by zeffii** [comment]
it will probably crash eventually. I had to rewrite a few things and the master version seems the most stable.

Yeah the icons were fun to make, but it made the code very 'bloated' .   enjoy if it works :)

**Comment by Spirou4D** [comment]
Zefii,
If I can, I want to correct the master last release with the icons, please?

**Comment by zeffii** [comment]
you are free to clone + fork the repository and distribute your own version where the icon's version is the master --  if you fix it in your own repo I will consider accepting a pull request to the icons branch here. 

I hope you can -- I gave up :)

**Comment by zeffii** [comment]
..but tinyCAD master will not include icons. I have no need for them.

**Comment by Spirou4D** [comment]
Yes but for my use only.

**Comment by zeffii** [comment]
please continue here:  https://github.com/zeffii/mesh_tinyCAD/issues/43

**Comment by zeffii** [comment]
http://codepen.io/zeffii/pen/pbRdOX
