### ISSUE TITLE
Blender 2.78c and TinyCad 1.3.0 are not playing well together (

### ISSUE THREAD

**Issue by helpmenowmark** [zeffii/mesh_tiny_cad#58]
![image](https://cloud.githubusercontent.com/assets/20262388/25076718/4d9937b2-22f1-11e7-826c-cced202a3bd2.png)

I have a simple mesh with two edges making a simple X.   The edges are on the same exact Z plane.
I am on Windows 8.1.   Regardless of the mode I am in, view port

I have tried to bring up the "Specials Menu" but I will admit the W hotkey fails to ever display.   I am in 
a 3D view, with Edge Select, and in Edit Mode (with both edges selected).    I am merely trying to bi-sect the edges at the point of edge intersection.

Any suggestions would be appreciated.   I re-installed blender 2.78c and I temporarily quit using Blender Sensei because they override some of the "normal" hotkeys.     

Thanks all.

**Comment by zeffii** [comment]
Try hitting space and typing vtx, to see the operator

**Comment by zeffii** [comment]
I will have a proper look later

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/25083320/b896e978-2356-11e7-9e2e-7fba45be3e92.png)

if W doesn't display specials then it's not really a tinyCAD issue/ and therefor not anything I can fix in the code. You could make a kb shortcut for the tinycad menu. `"VIEW3D_MT_edit_mesh_tinycad"`

I won't go into depth about how to make keyboard shortcuts:

![image](https://cloud.githubusercontent.com/assets/619340/25083563/080f1330-2358-11e7-8267-41160809d986.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/25083651/771da1c4-2358-11e7-874f-6e7b9b63f32d.png)

**Comment by helpmenowmark** [comment]
100% understood - I wanted to "fess up" from the beginning.   I can handle
it from here (hopefully I won't bother you again).  I've spent a couple of
days investigating this issue.  This is my first post and use of Github and
I wasn't very optimistic of  receiving a reply.  Just wow.

**Comment by zeffii** [comment]
hope it works out for you.

**Comment by helpmenowmark** [comment]
The overall problem was this:
[image: Inline image 1]
In my Blender's user preferences - I somehow had two keyboard shortcuts
(and both defined to the same shortcut key (W in this case).    I believe
all one has to do is to reassign the shortcut key to either "Subdivide" or
the "Call Menu" as shown above.
As part of the troubleshooting - I had to revert back to Blender's "Factory
Settings" and in fact this lead to other errors (where I couldn't even add
an object).   Consequently I reinstalled Blender 2.78c (in my case) and
installed with the "Repair" option (normal Microsoft Windows installation
choice).   I also Reinstalled TinyCad (of course).    I believe I still had
the same keyboard shortcut W still overriding the "Specials" keyboard
shortcut.  I believe the easier solution than reinstalling all the software
is to simply check off the selection "Subdivide" or to change the shortcut
Key to the Call Menu selection (shown).    I am unsure why (or how) the
Call Menu (for the Special Menu) and the Shortcut Key to W were assigned to
the same key.   I'll have to rely on the programmers such as yourself for
your expertise.

Thank you for your prompt reply(s).   It helped me diagnose the problem.

I have not had time to analyse or troubleshoot your routines but look
forward to their potential use.   They appear to be very clean and well
written.

Mark.

**Comment by zeffii** [comment]
Tiny CAD ( mesh_tiny_cad)  has shipped with Official Blender releases for about a year now, I hope you aren't downloading and installing it separately.

I learned Python just to write this add-on for Blender, so some code is old and verbose -- but it has been updated on numerous occasions -- and I do take some amount of pride in a working add-on. 

Let me know if you run into any unexpected behaviour from mesh_tiny_cad.

**Comment by helpmenowmark** [comment]
Yep, I did it.   I was reading dated documentation at the time. Sleep
depravation led to habitual reinstallation of Tiny-cad over the top a fresh
copy of Blender/Tiny cad (even when I specifically didn't want to).   I let
some oxygen to my brain last night.   All is well.

I am trying to learn Python for the exact same reason(s).   Your routines
were part of "the holy grail" I was looking to achieve.   This started the
installation frenzy and complete loss of version control.

Sorry.  I know better and did it any way.
