### ISSUE TITLE
re: e2f

### ISSUE THREAD

**Issue by meta-androcto** [zeffii/mesh_tiny_cad#59]
hi, i notice a crash/bug in edge to face where if the user selects an edge on the same vertical plane as the face, there's a crash/error reported:

```
Traceback (most recent call last):
  File "...\scripts\addons\mesh_tiny_cad\E2F.py", line 86, in execute
    extend_vertex(self)
  File "...\mesh_tiny_cad\E2F.py", line 63, in extend_vertex
    new_vertex = verts.new(new_co)
TypeError: verts.new(co)

location: <unknown location>:-1
```
thanks

**Comment by zeffii** [comment]
That must mean the edge never intersects the plane of the face, not a scenario i would use the operator on -- I can implement a fallback

**Comment by zeffii** [comment]
The failing scenario is something like this..
![image](https://user-images.githubusercontent.com/619340/29739945-6f746912-8a4b-11e7-8fbd-4306e8bc5c64.png)
The edge being extended towards the face lies on the same plane as the selected face, the same exception would happen if the edge was on a plane parallel to the selected face.

![image](https://user-images.githubusercontent.com/619340/29739963-db126ff2-8a4b-11e7-9ded-9979d08cab0e.png)

I can do a number of things here, my preference goes to a warning stating:
```
Edge2Face expects the edge to intersect at one point on the plane of the selected face. You're  
seeing this warning because mathutils.geometry.intersect_line_plane is being called on an edge/face  
combination that has no clear intersection point ( both points of the edge either touch the same  
plane as the Face or they lie in a plane that is offset along the face's normal )  
```

**Comment by zeffii** [comment]
i've commited a fix (rather ..code that mitigates the error being thrown... )

will try to push to Blender.org soon.

**Comment by zeffii** [comment]
users will now see this error if an edge never intersects the face:

![image](https://user-images.githubusercontent.com/619340/29741520-29d8ec2e-8a6f-11e7-964a-378bcfacc0e8.png)

the message in orange will display briefly in the warning/info report section of the header
