### ISSUE TITLE
Port on blender 2.8

### ISSUE THREAD

**Issue by Dalhana** [zeffii/mesh_tiny_cad#64]
Hello,
I am sad to see tinycad is no longer available through blender 2.8 and i was wondering if you will ever port it. It was one of the most used tool in my workflow and i would appreciate if it will come back.

Thanks you.

**Comment by zeffii** [comment]
i'll make a branch here that will work in 2.8 , the changes are minor ( i think )

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/49518423-ebd62000-f89e-11e8-94d3-c567dcd72765.png)

**Comment by zeffii** [comment]
small API changes will be throwing errors.. like
```python
 File "C:\Users\zeffi\Desktop\scripts\addons_contrib\mesh_tiny_cad\VTX.py", line 72, in remove_earmarked_edges
    bmesh.ops.delete(bm, geom=edges_select, context=2)
TypeError: delete: keyword "context" expected a string, not int
```

**Comment by zeffii** [comment]
BMeshOpFunc bmesh.ops.delete(bmesh, geom=[], context='VERTS')

**Comment by zeffii** [comment]
```c
/* del "context" slot values, used for operator too */
enum {
  DEL_VERTS = 1,
  DEL_EDGES,
  DEL_ONLYFACES,
  DEL_EDGESFACES,
  DEL_FACES,
  /* A version of 'DEL_FACES' that keeps edges on face boundaries,
   * allowing the surrounding edge-loop to be kept from removed face regions. */
  DEL_FACES_KEEP_BOUNDARY,
  DEL_ONLYTAGGED
};
```

**Comment by zeffii** [comment]
now that should be  https://docs.blender.org/api/blender2.8/bmesh.ops.html#bmesh.ops.delete
```
enum in ['VERTS', 'EDGES', 'FACES_ONLY', 'EDGES_FACES', 'FACES', 'FACES_KEEP_BOUNDARY', 'TAGGED_ONLY']
```

**Comment by zeffii** [comment]
https://github.com/zeffii/mesh_tiny_cad/pull/65

**Comment by Dalhana** [comment]
thank you very much
