### ISSUE TITLE
Blender 2.80 port of mesh_tiny_cad

### ISSUE THREAD

**Issue by Megalomaniak** [zeffii/mesh_tiny_cad#66]
Any ETA for when this might get ported to version 2.80(presuming there are plans to port this to 2.80)?

**Comment by Megalomaniak** [comment]
Ah, just noticed there is a branch for 2.80, downloading and testing now!

Oh god, yes! It works! This add-on has become such a vital part of my workflow I couldn't possibly live without it. :heart:

**Comment by zeffii** [comment]
done. master mesh_tiny_cad is now 2.80 only.  

last 2.79 release is archived in releases.

**Comment by zeffii** [comment]
this pull request updates tinycad master to work in 2.9x and 2.83
https://github.com/zeffii/mesh_tiny_cad/pull/73.
