### ISSUE TITLE
Menu v1.32 with thumnails???

### ISSUE THREAD

**Issue by Spirou4D** [zeffii/mesh_tiny_cad#72]
Hi Zeffii,
All is fine for you? I try to use your new release v1.32 on Blender 2.83 but I can't find your panel in dynamic menu in edit mode (lines)!
Is it normal because it's somewhere else......

**Comment by zeffii** [comment]
works in 2.9x , recent builds.

tinycad should still appear in the W menu.

![image](https://user-images.githubusercontent.com/619340/90343558-f3594080-e011-11ea-87b7-b80693c506a9.png)

**Comment by zeffii** [comment]
@Spirou4D  maybe start blender from console to see if there are any errors being displayed by tinycad when blender starts up.

**Comment by zeffii** [comment]
uhmmm..  this should be the master.  https://github.com/zeffii/mesh_tiny_cad/commits/tinycad_b28

**Comment by zeffii** [comment]
either way. the tinyCAD supplied with Blender is up to date. you don't need to download it from here.

but i have also updated it here (the master) https://github.com/zeffii/mesh_tiny_cad/pull/73

**Comment by zeffii** [comment]
while tinyCAD is supplied in the blender nightly builds,, and works,,  it may be a slightly different version,

i'm too lazy at this moment to check the differences.

**Comment by zeffii** [comment]
to avoid confusion i've changed the revision number to 1.3.3 here in master.

**Comment by Spirou4D** [comment]
Hi Zeffii very good your answer....I understood! I use the dynamic menu but I had forgotten this so good W menu!
All is ok! Thanks you so much!
All is nickel for you now?

**Comment by zeffii** [comment]
great.  yes should be cool now. : )
