### ISSUE TITLE
not working in 2.90 and 2.91 

### ISSUE THREAD

**Issue by soundsbeard** [zeffii/mesh_tiny_cad#76]
i enabled addon in both versions, but the search doesn't show 'vtx' function in both 2.90 and 2.91
also tried to install additional one from github.
both versions are stable, but may be it should work only in LTS blender?

**Comment by zeffii** [comment]
the version that ships with blender works in 2.92, which is what i use.

if you press W, the menu should appear with tinycad, else you should be getting errors in the info window.

**Comment by soundsbeard** [comment]
oh, its alt w in 2.8 input map, i got it.
i haven't been using it for a while, so was searching vtx like in 2.7 in a searchbar.
by bad. sorry for disturbing.

**Comment by zeffii** [comment]
nae worries. enjoy.
