### ISSUE TITLE
Operations not available in 3D View, context menu

### ISSUE THREAD

**Issue by sergeod9** [zeffii/mesh_tiny_cad#77]
Blender 2.92, Windows 10, RTX 2080
The add-on is checked and running, but when I click F3 and search for tinycad, or vtx ...etc it's not there.

**Comment by zeffii** [comment]
i think it's W or something now.. in edit mode.

**Comment by zeffii** [comment]
i'm closing this because there's nothing to do to it. But feel free to leave a comment.
